name: Custom 2

on:
  workflow_call:
    inputs:
      a:
        required: true
        type: string

  
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - id: a
        run: echo ${{ inputs.a}} | tr '-' '_' |  tr '[a-z]' '[A-Z]' >> $GITHUB_OUTPUT

      - run: echo ${{steps.a.outputs.value}}