name: Custom 2

on:
  workflow_call:
    inputs:
      a:
        required: true
        type: string

  
jobs:
  simple:
    runs-on: ubuntu-latest
    outputs:
      a1: steps.a.outputs.NAME
    steps:
      - id: a
        run: echo "NAME=$(echo ${{ inputs.a}} | tr '-' '_' |  tr '[a-z]' '[A-Z]')" >> $GITHUB_OUTPUT

      - run: echo ${{steps.a.outputs.NAME}}

  # Read-job:
    runs-on: ubuntu-latest
  #   needs: simple
  #   steps:
  #     - run: echo ${{ needs.simple.outputs.a1 }}

  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
    - id: step1
      run: echo "NAME=$(echo ${{ inputs.a}} | tr '-' '_' |  tr '[a-z]' '[A-Z]')" >> $GITHUB_OUTPUT
    - id: step2
      run: echo "test=world" >> $GITHUB_OUTPUT
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
    - run: echo ${{needs.job1.outputs.output1}} ${{needs.job1.outputs.output2}}