name: Custom 2

on:
  workflow_call:
    inputs:
      a:
        required: true
        type: string

  
jobs:
  simple:
    runs-on: ubuntu-latest
    outputs:
      app: steps.a.outputs.NAME
    steps:
      - id: a
        run: echo "NAME=$(echo ${{ inputs.a}} | tr '-' '_' |  tr '[a-z]' '[A-Z]')" >> $GITHUB_OUTPUT

      - run: echo ${{steps.a.outputs.NAME}}

  Read-job:
    runs-on: ubuntu-latest
    needs: simple
    steps:
      - run: echo ${{ needs.simple.outputs.app }}