name: Custom 2

on:
  workflow_call:
    inputs:
      a:
        required: true
        type: string

  
jobs:
  simple:
    environment: dev
    runs-on: ubuntu-latest
    outputs:
      transformed: ${{steps.a.outputs.NAME}}
      easy: ${{steps.f.outputs.NAME}}
      url: ${{steps.c.outputs.NAME}}
    env:
      UNENCRYPTED_MAIN: ${{ secrets.URL_M_A }}
    steps:
      - id: x
        name: x testing input
        run: echo ${{inputs.a}}

      - id: a
        name: a Setting transformation
        # run: echo "NAME=$(echo ${{ inputs.a }} | tr '-' '_' |  tr '[a-z]' '[A-Z]')" >> $GITHUB_OUTPUT
        run: echo "NAME=$(echo ${{ inputs.a }} | tr '-' '_')" >> $GITHUB_OUTPUT
      
      - id: b
        name: b testing transformation
        run: echo ${{steps.a.outputs.NAME}}
      
      - id: c
        name: c Setting env transformation
        run: echo "NAME=$(echo ${{ secrets[format('URL_{0}', steps.a.outputs.NAME)] }})" >> $GITHUB_OUTPUT
      
      - id: d
        name: d testing env transfotmation
        run: echo -n "${{steps.c.outputs.NAME}}" >> foo && cut -c1-3 foo && cut -c4 foo
                    
      - id: e 
        name: e testing secret output URL_M_A
        run: echo -n "${{ secrets.URL_M_A }}" >> foo && cut -c1-3 foo && cut -c4 foo

      - id: e2 
        name: e testing secret output URL
        run: echo -n "${{ secrets.URL }}" >> foo && cut -c1-3 foo && cut -c4 foo

      - id: e22 
        name: e mod testing secret output URL
        run: echo -n "${{ secrets.URL }}" >> foo && cut -c1-100 foo && cut -c 100- foo

      - id: e3 
        name: e testing secret output URL_M_A with python
        run: |
          import os
          for q in (os.getenv("UNENCRYPTED_MAIN")):
            print(q)
        shell: python
      
      - id: f
        name: f setting simple step output
        run: echo "NAME=$(echo 'hej')" >> $GITHUB_OUTPUT
      
      - id: g
        name: g testing simple step output
        run: echo ${{steps.f.outputs.NAME}}


  Read-job:
    environment: dev
    runs-on: ubuntu-latest
    needs: simple
    env:
        UNENCRYPTED_MAIN: ${{ secrets.URL_M_A }}
        URL: ${{ needs.simple.outputs.url }}
        URL_SCR: ${{ secrets[format('URL_{0}', needs.simple.outputs.transformed)] }}
    steps:
      - name: transformed
        run: echo ${{needs.simple.outputs.transformed}}

      - name: easy
        run: echo ${{needs.simple.outputs.easy}}

      - name: url
        run: |
          import os
          for q in (os.getenv("URL")):
            print(q)
        shell: python

      - name: url script
        run: |
          import os
          for q in (os.getenv("URL_SCR")):
            print(q)
        shell: python

      - name: url encript test
        run: |
          import os
          for q in (os.getenv("UNENCRYPTED_MAIN")):
            print(q)
        shell: python
  # job1:
  #   runs-on: ubuntu-latest
  #   # Map a step output to a job output
  #   outputs:
  #     output1: ${{ steps.step1.outputs.test }}
  #     output2: ${{ steps.step2.outputs.test }}
  #   steps:
  #   - id: step1
  #     run: echo "NAME=$(echo ${{ inputs.a}} | tr '-' '_' |  tr '[a-z]' '[A-Z]')" >> $GITHUB_OUTPUT
  #   - id: step2
  #     run: echo "test=world" >> $GITHUB_OUTPUT
  # job2:
  #   runs-on: ubuntu-latest
  #   needs: job1
  #   steps:
  #   - run: echo ${{needs.job1.outputs.output1}} ${{needs.job1.outputs.output2}}